json_content:
  class: audio_evals.process.base.ContentExtract
  args: {}


qwen_pretrain_asr_tractor_zh:
  class: audio_evals.process.qwen.QwenAudioASRExtract
  args:
    lang: zh

qwen_pretrain_asr_tractor:
  class: audio_evals.process.qwen.QwenAudioASRExtract
  args:
    lang: en
